apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io
    chart: bitnamicharts/wordpress
    targetRevision: 24.1.1
    helm:
      values: |
        global:
          storageClass: "local-path"
          imageRegistry: docker.io

        # WordPress main image
        image:
          repository: bitnami/wordpress
          tag: latest

        # MariaDB fix
        mariadb:
          image:
            repository: bitnami/mariadb
            tag: latest
          primary:
            persistence:
              storageClass: "local-path"
          # This fixes the Init:ImagePullBackOff for MariaDB
          volumePermissions:
            enabled: true
            image:
              repository: bitnami/os-shell
              tag: latest

        # Networking
        service:
          type: NodePort
          nodePorts:
            http: 30086

        wordpressPassword: "Loictining12345"
  destination:
    server: https://default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
