apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: wordpress
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 24.1.1

    helm:
      values: |
        global:
          storageClass: "local-path"

        image:
          repository: bitnami/wordpress
          tag: 6.7.1-debian-12-r5

        mariadb:
          auth:
            rootPassword: "rootpassword"
            password: "wordpresspass"

          primary:
            persistence:
              storageClass: "local-path"

          image:
            repository: bitnami/mariadb
            tag: 11.4.5-debian-12-r0

        service:
          type: NodePort
          nodePorts:
            http: 30086

        wordpressUsername: user
        wordpressPassword: "Loictining12345"

  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
